/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lad1lamlai;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class lab1bai2 extends javax.swing.JFrame {

    /**
     * Creates new form lab1bai2
     */
    public lab1bai2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntInput = new javax.swing.JButton();
        bntOption = new javax.swing.JButton();
        bntMessage = new javax.swing.JButton();
        bntConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntInput.setText("Input Dialog");
        bntInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInputActionPerformed(evt);
            }
        });

        bntOption.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntOption.setText("Option Dialog");
        bntOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOptionActionPerformed(evt);
            }
        });

        bntMessage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntMessage.setText("Message Dialog");
        bntMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMessageActionPerformed(evt);
            }
        });

        bntConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bntConfirm.setText("Confirm Dialog");
        bntConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntConfirm)
                    .addComponent(bntMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntInput)
                    .addComponent(bntMessage))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntConfirm)
                    .addComponent(bntOption))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMessageActionPerformed
        JOptionPane.showMessageDialog(this, "Please input your name");
    }//GEN-LAST:event_bntMessageActionPerformed

    private void bntInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInputActionPerformed
        String yourName = JOptionPane.showInputDialog("Your name is");
        if (yourName != null) {
            JOptionPane.showMessageDialog(null, "Your name is " + yourName);
        }


    }//GEN-LAST:event_bntInputActionPerformed

    private void bntConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConfirmActionPerformed
     int ret = JOptionPane.showConfirmDialog(this, "Are you sure",
             "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
              if(ret==JOptionPane.YES_OPTION){
              System.exit(0);
              
              }

    }//GEN-LAST:event_bntConfirmActionPerformed

    private void bntOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOptionActionPerformed
 int mesageType = JOptionPane.QUESTION_MESSAGE;
 String[] option = {"Java","C++","VB","PHP","Perl"};
 int code = JOptionPane.showOptionDialog(this, "What language do you prefer", "Option dialog box", 0, mesageType, null, option, "PHP");
        JOptionPane.showMessageDialog(this, "Answer" + code);
 
    }//GEN-LAST:event_bntOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab1bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab1bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab1bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab1bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab1bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConfirm;
    private javax.swing.JButton bntInput;
    private javax.swing.JButton bntMessage;
    private javax.swing.JButton bntOption;
    // End of variables declaration//GEN-END:variables
}
